Update backend-deploy.yml

diff --git a/.github/workflows/backend-deploy.yml b/.github/workflows/backend-deploy.yml
--- a/.github/workflows/backend-deploy.yml
+++ b/.github/workflows/backend-deploy.yml
@@ -84,15 +84,25 @@ jobs:
         continue-on-error: true
         with:
           image: ghcr.io/${{ github.repository }}/eventgallery-backend:${{ github.sha }}
-          args: --file=./code/backend/Dockerfile --severity-threshold=high --sarif-file-output=./snyk.sarif
+          args: --file=./code/backend/Dockerfile --severity-threshold=high --sarif-file-output=snyk.sarif
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+
+      - name: Verify SARIF file
+        run: |
+          ls -la
+          if [ -f "snyk.sarif" ]; then
+            echo "SARIF file exists"
+          else
+            echo "::error ::SARIF file not found"
+            exit 1
+          fi
 
       - name: Upload Snyk report
         uses: github/codeql-action/upload-sarif@v3
         if: always()
         with:
-          sarif_file: ./snyk.sarif
+          sarif_file: snyk.sarif
           category: snyk-docker
 
   update-k8s:
