Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -90,6 +90,12 @@ jobs:
             echo "Host *" > ~/.ssh/config
             echo "  StrictHostKeyChecking no" >> ~/.ssh/config
 
+            # Check if compose.prod.yaml file exists locally
+            if [ ! -f ./code/compose.prod.yaml ]; then
+              echo "File compose.prod.yaml not found!"
+              exit 1
+            fi
+
             # Upload docker-compose file to the server
             scp -o StrictHostKeyChecking=no ./code/compose.prod.yaml ec2-user@${{ secrets.DEPLOY_TARGET }}:/home/ec2-user/MSCV-Gallery-with-Face-Matching/code/compose.prod.yaml
 
